type EventCategory = 'global' | 'controlKey' | 'keyCode' | 'mouse' | 'change' | 'wheel'


const Keys = [
	'Backspace',
	'Tab',
	'Clear',
	'Enter',
	'Control',
	'Alt',
	'CapsLock',
	'Escape',
	'PageUp',
	'PageDown',
	'End',
	'Home',
	'ArrowLeft',
	'ArrowUp',
	'ArrowRight',
	'ArrowDown',
	'Insert',
	'Delete',
	'0',
	'1',
	'2',
	'3',
	'4',
	'5',
	'6',
	'7',
	'8',
	'9',
	'A',
	'B',
	'C',
	'D',
	'E',
	'F',
	'G',
	'H',
	'I',
	'J',
	'K',
	'L',
	'M',
	'N',
	'O',
	'P',
	'Q',
	'R',
	'S',
	'T',
	'U',
	'V',
	'W',
	'X',
	'Y',
	'Z',
	'a',
	'b',
	'c',
	'd',
	'e',
	'f',
	'g',
	'h',
	'i',
	'j',
	'k',
	'l',
	'm',
	'n',
	'o',
	'p',
	'q',
	'r',
	's',
	't',
	'u',
	'v',
	'w',
	'x',
	'y',
	'z',
	'Meta',
	'F1',
	'F2',
	'F3',
	'F4',
	'F5',
	'F6',
	'F7',
	'F8',
	'F9',
	'F10',
	'F11',
	'F12',
]

const Codes = [
	'NumLock',
	'ControlLeft',
	'AltLeft',
	'Space',
	'MetaLeft',
	'MetaRight',
	'NumpadMultiply',
	'NumpadAdd',
	'NumpadSubtract',
	'NumpadDecimal',
	'NumpadDivide',
	'Semicolon',
	'Equal',
	'Comma',
	'Minus',
	'Period',
	'Slash',
	'Backquote',
	'BracketLeft',
	'Backslash',
	'BracketRight',
	'Quote'
]

const KeyCodes = [...Keys, ...Codes]

const ControlKeys = ['Ctrl+', 'Alt+', 'Shift+', 'Ctrl+Alt+', 'Ctrl+Shift+', 'Alt+Shift+', 'Ctrl+Alt+Shift+']


export const LuposDomEventModifiers: Record<EventCategory, CompletionItem[]> = {
	global: [
		{name: 'capture', description: 'Trigger event only on capture phase, not bubble phase.'},
		{name: 'self', description: 'Trigger event only when event target is current element, not descendant elements.'},
		{name: 'once', description: 'Trigger event for only once.'},
		{name: 'prevent', description: 'Prevents default action for event.'},
		{name: 'stop', description: 'Stops event propagation.'},
		{name: 'passive', description: 'Browser will not wait listener to execute completed before painting.'},
	],
	controlKey: ControlKeys.map(key => ({name: key, description: ''})),
	keyCode: KeyCodes.map(key => ({name: key, description: ''})),
	mouse: [
		{name: 'left', description: 'Trigger mouse event only when interact with left button.'},
		{name: 'middle', description: 'Trigger mouse event only when interact with middle button.'},
		{name: 'right', description: 'Trigger mouse event only when interact with right button.'},
		{name: 'main', description: 'Trigger mouse event only when interact with main button.'},
		{name: 'auxiliary', description: 'Trigger mouse event only when interact with auxiliary button.'},
		{name: 'secondary', description: 'Trigger mouse event only when interact with secondary button.'},
	],
	change: [
		{name: 'check', description: 'Trigger change event only when input becomes checked.'},
		{name: 'uncheck', description: 'Trigger change event only when input becomes unchecked.'},
	],
	wheel: [
		{name: 'up', description: 'Trigger wheel event only when wheel up.'},
		{name: 'down', description: 'Trigger wheel event only when wheel down.'},
	],
}


export const LuposEventCategories: Record<string, EventCategory> = {
	keydown: 'keyCode',
	keyup: 'keyCode',
	keypress: 'keyCode',
	mousedown: 'mouse',
	mousemove: 'mouse',
	mouseup: 'mouse',
	click: 'mouse',
	dblclick: 'mouse',
	change: 'change',
	wheel: 'wheel',
}
